# Generated by Django 5.2.8 on 2025-11-15 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='Profile name')),
                ('login', models.CharField(max_length=250, unique=True, verbose_name='Login Name')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=250, verbose_name='Password')),
                ('repeat_password', models.CharField(max_length=250, verbose_name='Repeat Password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
