# Generated by Django 5.2.8 on 2025-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
    ]
