# Generated by Django 5.2.8 on 2025-11-19 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только кириллические буквы, дефис и пробелы.', regex='^[а-яА-ЯёЁ\\- ]+$')], verbose_name='ФИО'),
        ),
    ]
