# Generated by Django 5.2.8 on 2025-11-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_alter_userprofile_full_name_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
