# Generated by Django 5.2.8 on 2025-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_application_status_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
    ]
